name: the grumpy cooker
favicon: null
layout_spectrum: 0.25247
typography_spectrum: 0.61239
title: the grumpy cooker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d50071'
    - '#fe8d00'
    - '#00b361'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
